version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
    depends_on: 
      - api
      - web
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: redis:latest
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules/ #don't overwrite inside container
      - ./api/:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDB=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  web:
    build:
      context: './web'
      dockerfile: Dockerfile.dev 
    stdin_open: true
    tty: true
    volumes: 
      - /app/node_modules
      - './web:/app'
    environment: 
      - CHOKIDAR_USEPOLLING=true